### ISSUE TITLE
[BUG] Content Failing to Load [Issue #100!]

### ISSUE THREAD

**Issue by hoarybat70** [Cattn/gba#100]
**Describe the bug**
Whenever I try to load a game on the website that belongs to either the NES, SNES, or GBA, I get approached with an error screen from what appears to be RetroArch. For example, if I try to load Final Fantasy 5 (the game that I have been playing on this website for about a month now; fifteen hours in), it loads as usual but after loading the game data the error screen begins to pop up and it claims that it could not read the zip file.

**To Reproduce**
1. Go to any SNES, NES, or GBA emulator game.
2. Click on the game and load.
3. See error

**Expected behavior**
I was expecting the video game to load as per usual.

**Screenshots**
![image](https://user-images.githubusercontent.com/119082939/219880094-d428eb14-fd6b-4093-a724-30777741acae.png)

**Windows Or Chromebook?**
Chromebook

**Comment by Cattn** [comment]
Is this on a fork?

**Comment by hoarybat70** [comment]
> Is this on a fork?

I don't believe so. I'm not an expert on this so I'm not exactly sure. I was using this website (https://cattn.github.io/gba/launchpad.html) if this helps.

**Comment by Cattn** [comment]
Yes that helps, you were correct, 

quick question: Are you able to access dev-console? (hit ctrl-shift-i)

**Comment by hoarybat70** [comment]
Whenever I do try hitting CTRL-SHIFT-I a menu does pop up. I've included an image if that helps. I'm not quite sure whether that is dev-console or not, however.

![image](https://user-images.githubusercontent.com/119082939/219905555-7268983d-b182-4538-9f82-f3f4134dc607.png)

**Comment by Cattn** [comment]
So no menu on the right side of your screen (not within retroarch/game) pops up?

otherwise, that's not the dev console, but that's fine

Please paste the code below into your bookmarks bar, and just click the bookmark when on the page, and please send a picture of the text that pops up when you click it

``javascript:var%20themeInfo%3DlocalStorage.getItem(%22theme%22)%2CcustomHostInfo%3DlocalStorage.getItem(%22custHost%22)%2CuseCustomHostInfo%3DlocalStorage.getItem(%22is1Check%22)%2CuseAltHostInfo%3DlocalStorage.getItem(%22isCheck%22)%2CuseNetPlayInfo%3DlocalStorage.getItem(%22isNet%22)%2CuseAltNdsHostInfo%3DlocalStorage.getItem(%22doGitHack%22)%3Balert(%22Theme%3A%20%22%2BthemeInfo%2B%22%20Custom%20Host%3A%20%22%2BcustomHostInfo%2B%22%20Use%20Custom%20Host%3A%20%22%2BuseCustomHostInfo%2B%22%20Use%20Alt%20Host%3A%20%22%2BuseAltHostInfo%2B%22%20Use%20NetPlay%3A%20%22%2BuseNetPlayInfo%2B%22%20Use%20Alt%20NDS%20Host%3A%20%22%2BuseAltNdsHostInfo)%3Bvoid+0``

**Comment by hoarybat70** [comment]
> So no menu on the right side of your screen (not within retroarch/game) pops up?
> 
> otherwise, that's not the dev console, but that's fine
> 
> Please paste the code below into your bookmarks bar, and just click the bookmark when on the page, and please send a picture of the text that pops up when you click it
> 
> `javascript:var%20themeInfo%3DlocalStorage.getItem(%22theme%22)%2CcustomHostInfo%3DlocalStorage.getItem(%22custHost%22)%2CuseCustomHostInfo%3DlocalStorage.getItem(%22is1Check%22)%2CuseAltHostInfo%3DlocalStorage.getItem(%22isCheck%22)%2CuseNetPlayInfo%3DlocalStorage.getItem(%22isNet%22)%2CuseAltNdsHostInfo%3DlocalStorage.getItem(%22doGitHack%22)%3Balert(%22Theme%3A%20%22%2BthemeInfo%2B%22%20Custom%20Host%3A%20%22%2BcustomHostInfo%2B%22%20Use%20Custom%20Host%3A%20%22%2BuseCustomHostInfo%2B%22%20Use%20Alt%20Host%3A%20%22%2BuseAltHostInfo%2B%22%20Use%20NetPlay%3A%20%22%2BuseNetPlayInfo%2B%22%20Use%20Alt%20NDS%20Host%3A%20%22%2BuseAltNdsHostInfo)%3Bvoid+0`

Ah, I should clarify. There is a menu that does pop up sometimes, but said menu does disappear rather quickly. 

I wasn't quite sure how to format the code (I don't know if pasting in the bookmarks bar is something exclusive to Github or if I'm jut looking in the wrong place) but when I did try to place it in the javascript _website_ (may be wrong?) I got this.

![image](https://user-images.githubusercontent.com/119082939/219906005-7a926eac-b481-4ce2-9672-7a7a84edc974.png)

Thank you for being patient! It means a lot. :)

**Comment by Cattn** [comment]
Right click on your ``Bookmarks Bar`` As shown in photo attached, and then hit paste after copying the code

The option will be available to you if you copied the code with the javascript: at the beginning not javascript.com

**Comment by Cattn** [comment]
![image](https://user-images.githubusercontent.com/69491394/219906202-9b60e639-9c88-4a92-bc33-731d38879daf.png)

**Comment by hoarybat70** [comment]
I right-clicked the bookmark bar, copied and pasted the text, and saved it as a bookmark, but it doesn't load regardless. Am I doing something wrong? 

![image](https://user-images.githubusercontent.com/119082939/219906712-32005258-ac1b-4618-93af-d283e56cc044.png)

**Comment by Cattn** [comment]
Okay, so did you try clicking the bookmark while on our site?

**Comment by hoarybat70** [comment]
Yes, I did. It still didn't work.

**Comment by Cattn** [comment]
Alright, bookmarklets may be disabled on your PC. Can you go to: https://cattn.github.io/gba/dev.html and click on a game there, and tell me if the same error happens?

**Comment by Cattn** [comment]
Also, can you go to https://cattn.github.io/gba/settings.html and take a picture of all of your settings?

**Comment by hoarybat70** [comment]
> Alright, bookmarklets may be disabled on your PC. Can you go to: https://cattn.github.io/gba/dev.html and click on a game there, and tell me if the same error happens?

The same error does occur.



> Also, can you go to https://cattn.github.io/gba/settings.html and take a picture of all of your settings?

![image](https://user-images.githubusercontent.com/119082939/219963907-26e86b40-4c68-41f0-ab8f-4f8206223353.png)

**Comment by hoarybat70** [comment]
I assume just by this that I should just turn "netplay" on, although assuming the settings were the same the entire time it does make me wonder how it was working for a month before this happened. Perhaps the settings changed somehow?

**Comment by hoarybat70** [comment]
Update: I turned NetPlay back on and the emulators work now. Thank you for all of your help! :)

**Comment by Cattn** [comment]
This is really really really weird, normally netplay being on allows for things to start breaking, not the other way around, but hey! if it works for you, that's good. netplay will use the older cores, and that may be a bit slower for you.
