### ISSUE TITLE
Pokemon Infinte fusion

### ISSUE THREAD

**Issue by Rillboom10** [Cattn/gba#103]
yes
no

I don't know

**Comment by alantheraboot** [comment]
its a fangame, not a rom hack. he cant add it

**Comment by Cattn** [comment]
Pokemon rom request - specifically fangames may be added (no guarantee), and if so very slowly due to the sheer amount we get suggested. Please be patient, thank you.

**Comment by Mekomancer** [comment]
pokemon infinte fusion runs on windows

**Comment by Mekomancer** [comment]
pls close as not planned @Rillboom10
