### ISSUE TITLE
[ROM REQUEST]

### ISSUE THREAD

**Issue by GithubMaster348** [Cattn/gba#105]
**Is this a ROM hack?**
No.
**Do you have a link to the ROM?**
[Yes](https://archive.org/download/nintendo-64-romset-usa)
**Does this ROM require patching?**
No.
**Anything Extra**
You Also Need to Add A N64 emulator. I know It's possible because emulator js supports it.

**Comment by Mekomancer** [comment]
Please close as n64 roms have been added to the website @GithubMaster348
