### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Hazard368** [Cattn/gba#106]
**Describe the bug**
When I press play on any DS game it loads for a couple seconds and then shows "Network Failure"

**To Reproduce**
1. Go to the home page
2. Click on DS Simulator
3. Scroll down to any of the DS games

**Expected behavior**
I expected the game to start like how the GBA and N64 games start, as they are working

**Screenshots**
no screenshots sorry

**Windows Or Chromebook?**
I only tried it on Windows so far.

**Additional context**
The DS games just won't load, the one game specifically I was trying to load was Mario Kart DS, but I tried with other DS games and it still didn't work. I've tried this on multiple devices in different locations so I'm pretty sure it's not my connection that is causing it.

**Comment by Hazard368** [comment]
unless the ds games are blocked which might be the issue, I'm not sure

**Comment by Cattn** [comment]
Try switching the host in nds.html, It's because our sources are blocked for you.

**Comment by Hazard368** [comment]
I tried that and it still doesn't work

**Comment by Cattn** [comment]
try visiting homepage, I have since fixed this
