### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Mymomisdumb** [Cattn/gba#112]
**Describe the bug**

Pokemon heart gold keeps saying network error. My friend also tryed. Didnt work.

**To Reproduce**
1. Go to 'DS Emulator'
2. Click on 'page 2'
3. search to 'pokemon'
4. scroll and it will be the first one
5. wait and see error

**Expected behavior**
in red, it will say Network Error
**Screenshots**

**Windows Or Chromebook?**
Please state which device you are on
Chromebook
**Additional context**
nothing else

**Comment by Cattn** [comment]
This is a duplicate, also visit the homepage I have since tried to correct this bug.
