### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by NathanZ-on-github** [Cattn/gba#113]
**Describe the bug**

**To Reproduce**
1. Go to 'DS Emulator (NEW! + FIXED)'
2. Click on 'Next Page (Page 2)'
3. Scroll down to actually any game
4. Click Start Game
5. Behold!, Game Core ready, Network Error

**Expected behavior**
I expected the game to load (pokemon platinum specifically)
**Screenshots**
Attached
**Windows Or Chromebook?**
Please state which device you are on
Chromebook
**Additional context**
Nah
![Screenshot 2023-03-11 5 40 08 PM](https://user-images.githubusercontent.com/100717113/224519618-72208cb9-8502-4397-b2e3-48e51a9cb56c.png)

**Comment by Cattn** [comment]
DS games are blocked for you likely

**Comment by NathanZ-on-github** [comment]
Well, it loaded once, and I could play 1 vs 100, then my computer ran out
of battery, and it wouldn't load again.

**Comment by Cattn** [comment]
Oh, that's a weird issue, have you tried swapping the provider on nds.html?

**Comment by Cattn** [comment]
@NathanZ-on-github Please respond or I will close this, I have made network-related updates recently, visit the homepage and try again

**Comment by NathanZ-on-github** [comment]
It's working. Thanks.

**Comment by Cattn** [comment]
Ty for responding!
