### ISSUE TITLE
Change Ad Scheme/Type of Ads

### ISSUE THREAD

**Issue by gaster2411** [Cattn/gba#131]
these ads are getting out of hand. i completely understand that this project needs funding and i am 100% for ads, but these..are genuinely getting too ridiculous. for an example, when I try to access the website it immediately redirects to a website like "https://overheatusa.com/uZb1pKZFNUltFMF4-sEQF_bSE6ts6qhTLhW1rCd8O8o/?cid=225fca16ddd41d8b177e8d20d4021337&sid=16122660". Sometimes, just clicking a button will redirect these sites. My suggestion is to put ads on the sides of the screen, and add something like patreon to access 3ds games. alternatively, you can add something like "buy me a coffee".
thanks,
gaster

**Comment by Cattn** [comment]
Thank you for the suggestion, I'll try and tone down the full screen ads, although for almost all the popup ads the X is in the top right corner (kinda hidden), I will try and stick with banner ads mostly. 

Thank you very much for the feedback.

**Comment by Cattn** [comment]
I will close this when I've made these changes

**Comment by gaster2411** [comment]
reopening because the ads are back lol
https://exusnefte.com/land?c=DHU7EXg3rvaMPk2kDfc1QohNEmg%3D&cnv_id=228839ad70fefd18c89931b7bcfd0d94&placement=19106968&campaign=687670

**Comment by NikkiSixx123** [comment]
It's been happening to me too, and there's no x buttons in the corners or anything

**Comment by Cattn** [comment]
Can you please send a screenshot because I only meant to add banner ads, and nothing else should be there

**Comment by NikkiSixx123** [comment]
It just got fixed for me, I don't have screenshots

**Comment by NikkiSixx123** [comment]
I'll notify you if it happens again

**Comment by gaster2411** [comment]
here you go lol
[Screen recording 2023-05-02 8.21.17 AM.webm](https://user-images.githubusercontent.com/121835599/235765352-42e29a66-7248-4669-a13a-a469473b4a91.webm)

**Comment by Nailington** [comment]
@gaster2411 That was yesterday??? I am going to forward this to @Cattn!

I have made it clear, and Cat agrees with me, that full screen or redirects are not tolerated. Thanks for bringing this to our attention.

**Comment by Cattn** [comment]
> here you go lol [Screen recording 2023-05-02 8.21.17 AM.webm](https://user-images.githubusercontent.com/121835599/235765352-42e29a66-7248-4669-a13a-a469473b4a91.webm) don't mind the lagginess, i filmed this at school

Hey, thank you for sending this, yesterday in my ad panel I disabled some extra categories (which shouldn't matter as all I've added to the site are banner ads, and there should not be any other type of ads. Please let me know today if it's better for you?

If it doesn't get better I'll disable ads entirely, and will figure something out later as I've been very sick the past few days and don't have the time to deal with it fully

**Comment by Cattn** [comment]
> It just got fixed for me, I don't have screenshots

This was around the time that I turned off those modules I think, so maybe @gaster2411 clear your cache and it'll be better now? If not I'll remove ads, and send them a long email

**Comment by Cattn** [comment]
Just removed all ads
