### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Bread123456gba** [Cattn/gba#136]
Where did radical red go?
It was by far the best game here

**Comment by Nailington** [comment]
It is currently misconfigured, should be back soon!

**Comment by Bread123456gba** [comment]
Thank you for your prompt response. Looking forward to it. :)

**Comment by Cattn** [comment]
should be fixed in https://github.com/Cattn/GBA2.0/commit/d43148261c2ae929384e0fad468ef6d801486b32

Changes should be live within 5 or so minutes, thank you for the report!

**Comment by Bread123456gba** [comment]
Tysm
