### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Luigifa** [Cattn/gba#139]
**Describe the bug*
The emulator works great, but Smash 64 one my favorite games doesn't work. I don't think this could be fixed, but the DS play super slow, and also a 3DS emulator would be great, also a wii emulator, I'm sure the last too won't happen, but I still wanted to put  that out there. 
From LuigiFan1

**To Reproduce**

**Expected behavior**

**Screenshots**

**Windows Or Chromebook?**
Please state which device you are on

**Additional context**

**Comment by Cattn** [comment]
Should be a bit better after recent update, but other than that likely your device being slow

(3ds emulator isn't possible sadly)
