### ISSUE TITLE
Mega Man and Bass

### ISSUE THREAD

**Issue by Batmanmk** [Cattn/gba#140]
## Is this a rom hack?
Could be, if English translations are counted

## Do you have a link to the ROM?
**Please note that having a link raises the chance of it being added**
No, I can not find one.

## Does this ROM required patching?
An English fan translation.

## Anything Extra
Originally a Japanese exclusive SNES game, a unofficial fan translated version does exist.

**Comment by Nailington** [comment]
@Batmanmk Do you by chance have the Japanese rom? I can go looking for it, but the base rom would go a long way.

**Comment by Batmanmk** [comment]
I do have it, but I don’t know how to put it on here.

**Comment by Nailington** [comment]
Fork [the gba-host repo](https://github.com/cattn/gba-host) and upload it in the /snes-alt folder (should be able to do so in browser, if not just let me know and I will start looking for it myself). If you can do that, please create a Pull Request so I can add it formally.

**Comment by Batmanmk** [comment]
Yeah, I’m too confused to do it. Been trying for half an hour and still can’t get it.

**Comment by Nailington** [comment]
No worries then :)

**Comment by Batmanmk** [comment]
So what now? Are you still going to put the game in?

**Comment by Batmanmk** [comment]
I got the site where I got the original rom. Hope this helps if you haven’t already found it yourself.

https://www.emulatorgames.net/roms/super-nintendo/rockman-forte

**Comment by Nailington** [comment]
nice, thanks

**Comment by Batmanmk** [comment]
Hey, just wanted to check in. Any chance you found the rom?

**Comment by Cattn** [comment]
@Nailington

**Comment by Nailington** [comment]
I actually just now downloaded the rom, and what I think is an English Translation Patch. It may take some time before it appears on our site, but it is being worked on! I will probably only add it on GBA2.0 btw, but still TBD on that decision.

@Cattn if at some point you can refresh me on the procedure for adding a new rom lol?

**Comment by Batmanmk** [comment]
If you need a good English translation patch, then might I direct you to the Aeon Genesis fan translation?

**Comment by Batmanmk** [comment]
I’m trying to find the Aeon Genesis translation so that you can easily input it, but I think the translation is only available on actual physical reproduction cartridges.

**Comment by Nailington** [comment]
That is the one I got!

Will be adding soon both the original rom and the patched one (I’m choosing the Americanized names btw)

**Comment by Cattn** [comment]
> I actually just now downloaded the rom, and what I think is an English Translation Patch. It may take some time before it appears on our site, but it is being worked on! I will probably only add it on GBA2.0 btw, but still TBD on that decision.
> 
> @Cattn if at some point you can refresh me on the procedure for adding a new rom lol?

Go to a console's proper json folder, and just add the game to the bottom of the list, or top, or in alphabetical if you care

**Comment by BatmanMk2** [comment]
I just found the game on GBA 2.0, but there a weird screen that doesn’t allow me to play it.

(Also, I’m on a new account. I don’t know why I decided to delete the old one. But I did without realizing it until it was already done.)

**Comment by Cattn** [comment]
Can you send the link to the game?

**Comment by BatmanMk2** [comment]
Here. Hope it works.

https://www.emulatorgames.net/roms/super-nintendo/rockman-forte

**Comment by Cattn** [comment]
I mean the game on GBA2.0 so that I can try and see what the issue is

**Comment by BatmanMk2** [comment]
Never mind. I found the translated rom on the 1.0, but it doesn’t work is on 2.0. Here’s a picture on the 2.0.

![image](https://github.com/Cattn/gba/assets/139914935/240c2d4f-d86f-414f-b498-39ceed2884c7)

**Comment by BatmanMk2** [comment]
That is the screen I get whenever I boot it up.

**Comment by Nailington** [comment]
I dont actually remember adding rockman.... but i might have?
