### ISSUE TITLE
PS1 ROMS

### ISSUE THREAD

**Issue by Mekomancer** [Cattn/gba#149]
**Is your feature request related to a problem? Please describe.**
I want to play tekken

**Describe the solution you'd like**
Add a PS1 ROM collection

**Describe alternatives you've considered**
Save this as a feature for GBA2.0
Fork Repo and make the changes my self

**Additional context**
Happy to give list of PS1 ROMS
The emulator already supports PS1
![image](https://github.com/Cattn/gba/assets/79238580/c6ec5005-4df4-44d5-be4b-ac0081183e61)

**Comment by Mekomancer** [comment]
Should I make this a feature for GBA2.0 or GBA

**Comment by Nailington** [comment]
So I have actually experimented with this back before even 1.0 was public (we were still building site even)... PS1 and up are WAYYYY to large to conceivably store, let alone host. I have no idea how I would even clone it locally to push onto a repo. I also have my sources for roms, and have an easy download list for PS1, but I have 0 method of serving.

**Comment by Mekomancer** [comment]
I'm on a restricted computer and can't access the download pages
is there a way you could send me the Tekken (1) rom.

**Comment by Cattn** [comment]
yeah I'd love to do this, but it's almost impossible to serve them (nds games working is a miracle)
