### ISSUE TITLE
[BUG] i'm playing pokemon (on my chromebook) and my cheats don't work. i know this is to much to ask but can you add an option where you can enable the cheats. and if not then just fix the cheats menu

### ISSUE THREAD

**Issue by javabruh** [Cattn/gba#176]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Windows Or Chromebook?**
Please state which device you are on

**Additional context**

**Comment by Cattn** [comment]
Hello, please visit their discord and ask there. https://discord.com/invite/6akryGkETU
