### ISSUE TITLE
[BUG] Cheats bug

### ISSUE THREAD

**Issue by javabruh** [Cattn/gba#177]
[BUG] i'm playing Pokemon (on my Chromebook) and my cheats don't work. i know this is to much to ask but can you add an option where you can enable the cheats. and if not then just fix the cheats menu

**Comment by Qinx99** [comment]
there is a cheats tab but the cheats don't work

**Comment by Qinx99** [comment]
for some reason

**Comment by Cattn** [comment]
Hello, please visit their discord and ask there. https://discord.com/invite/6akryGkETU
