### ISSUE TITLE
Pokemon Radical Red Cheat Codes Not Working

### ISSUE THREAD

**Issue by FlyAwayGarlic59** [Cattn/gba#191]
**Describe the bug**
So I'm stuck on a part in Pokemon Radical Red and would like to use some cheats, but the cheat codes aren't working.

**To Reproduce**
1. open the rom file and load a save or go through the intro
2. Go to 'cheats'
3. select 'add cheat'
4. input the master code and then the cheat code (I tried the instant kill one)

**Expected behavior**
the cheat doesn't work, nothing happens

**Screenshots**
N/A

**Windows Or Chromebook?**
Windows

Also I'm playing on https://math-study.github.io/gba

**Comment by Cattn** [comment]
Hello, please visit their discord and ask there. https://discord.com/invite/6akryGkETU
