### ISSUE TITLE
[FORM] Ruffle emulator

### ISSUE THREAD

**Issue by proudparrot2** [Cattn/gba#48]
**Place Suggestion/Bug below**
I know your website is about GBA and Nintendo Consoles but could you add a Ruffle Emulator of some sort so people can play Ruffle Games.

**Comment by proudparrot2** [comment]
Side note from me: https://replit.com/@ParrotDev/dynamicruffle

**Comment by Cattn** [comment]
This will be added to MSGV2 I'm adding wontfix because it won't be implemented here
