### ISSUE TITLE
[FORM] RetroArch go brrr

### ISSUE THREAD

**Issue by proudparrot2** [Cattn/gba#49]
**Place Suggestion/Bug below**
now I know this sounds stupid but I cannot run any ds emulators it will just send me to a menu that says "Main Menu". sadness

**Comment by proudparrot2** [comment]
also a bug but I can't add that label *sadness*

**Comment by Cattn** [comment]
Hello, please try swapping the provider in nds.html, if that doesn't work it's probably blocked for you. Sorry!
