### ISSUE TITLE
[FORM] Feature requests

### ISSUE THREAD

**Issue by proudparrot2** [Cattn/gba#52]
**Place Suggestion/Bug below**
yo.... this is the same guys who asked for unbound and the ds emu again, bro u r a legend, how do u do all of this, like we really appreciate it and me and my friend were talking about how its not possible to patch some downloaded rom files on our chromebooks so I wanted to know if there was any possible way you could (i dont really know what i am saying right now) somehow find a way to embedd a file patcher on this website, that somehow gets through our annoying school firewall and yea. I know it sounds impossible(it probably is) but could you plz try? I know this is a huge request but can you also please try and add a nintendo 3ds emulator because I am a big fan of pokemon games and I have always wanted to play an open world game so please? also can u plz contact me at **censored** I dont have discord.... and my friend may have got on your discord because he said he did and he got the link to the math study site. Alright please try to make this possible... My biggest thank u.

**Comment by Cattn** [comment]
Yes! File patcher was added in https://github.com/Cattn/gba/commit/680e737f4aaaf3de1b02c0899b3b31a505bdb94a credit to https://github.com/marcrobledo/RomPatcher.js/

As for 3DS I'm not sure would have to ask EmulatorJS
