### ISSUE TITLE
[FORM] Framerate on DS

### ISSUE THREAD

**Issue by proudparrot2** [Cattn/gba#55]
**Place Suggestion/Bug below**
Hey, I play on a HP school chrome book. While playing on the DS emulator, I have continuous frame rate issues. On things like Animal Crossing Wild World my FPS is in the 10s. The only games that really work are games like cooking mama. It’s fine if there’s no way to fix this, just a little issue I’ve had.  

> Cat, are there any ways to improve this?

**Comment by Cattn** [comment]
Hey! This isn't something we can help with sadly, the only thing I can suggest is to make sure you don't have too many tabs open, not too much we can do (can try asking EmulatorJS)
