### ISSUE TITLE
[ROM REQUEST]

### ISSUE THREAD

**Issue by alantheraboot** [Cattn/gba#56]
**Is this a rom hack?** Yes this is a rom hack,

**Do you have a link to the ROM?** Yes, a google drive link- https://drive.google.com/drive/folders/18tJz5rJikXKMklvhRdVT8IMDzMZ5x3Tu?usp=share_link

**Does this ROM required patching?** No, it is pre-patched.

**Anything Extra**
This is an nds rom file

**Comment by Cattn** [comment]
Hello, I see the ROM, we will be adding it soon, it is a bit of a process for us to add nds roms.

**Comment by alantheraboot** [comment]
Yeah okay!, thanks Cattn. Love your website!

**Comment by Cattn** [comment]
Thank you!

**Comment by Cattn** [comment]
I'll mark this as complete when It's added

**Comment by alantheraboot** [comment]
is it added

**Comment by Cattn** [comment]
It isn't. we haven't updated nds in a while due to technical issues, @Nailington will be on this however

**Comment by Nailington** [comment]
The rom is over 100MB, therefore it isnt able to be added... Sorry for the disappointment @alantheraboot 


@Cattn
