### ISSUE TITLE
[FORM] Mario kart 64 link?

### ISSUE THREAD

**Issue by proudparrot2** [Cattn/gba#66]
**Place Suggestion/Bug below**
Hey there used to be a mario kart 64 link here in gba but now its gone i could never find it it was my favorite game so i was just wondering if you moved the link

**Comment by Cattn** [comment]
Closest we have, we don't have n64 games for the most part 
https://math-study.github.io/gba/launchpad.html?gameID=7857&gametitle=Mario_Kart_DS_(USA)_(EnFrDeEsIt)&fav=true
