### ISSUE TITLE
[ROM REQUEST]

### ISSUE THREAD

**Issue by Mekomancer** [Cattn/gba#72]
**Is this a rom hack?**
Yes
**Do you have a link to the ROM?**
https://smash64.online/remix And https://mekomancer.github.io/gdata/Super%20Smash%20Bros.%20(U)%20[!].z64
**Does this ROM required patching?**
Yes
**Anything Extra**

**Comment by JavaScythe** [comment]
queued for next commit

**Comment by Mekomancer** [comment]
Thanks

**Comment by Cattn** [comment]
Hello, this is being queued for our N64-Rom Release. Thank you!

-- Lead Developer, Cattn

**Comment by Cattn** [comment]
Being added in https://github.com/Cattn/gba/commit/f89cf66b79149724d0ca4cc46eaec813ccb01c9e currently
