### ISSUE TITLE
[BUG]DS still won't work it says NETWORK ERROR in RED *PLS* FIX

### ISSUE THREAD

**Issue by alucard7maniac** [Cattn/gba#73]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Windows Or Chromebook?**
Please state which device you are on

**Additional context**

**Comment by Cattn** [comment]
Please fill out the form next time, anyway please tell me which games show red? NDS? if so, tell me if githack, or replit is blocked for you

**Comment by Cattn** [comment]
I think this has been fixed since, anyway duplicate
