### ISSUE TITLE
[ROM REQUEST]

### ISSUE THREAD

**Issue by Mekomancer** [Cattn/gba#84]
**Is this a rom hack?**
Yes
**Do you have a link to the ROM?**
[smashremix1.2.2.z64.7z.zip](https://github.com/Cattn/gba/files/10552095/smashremix1.2.2.z64.7z.zip)
**Does this ROM required patching?**
Already patched
**Anything Extra**
I had to Compress the file as 7z for size, and then zip to upload to github.
Love your site, its amazing.

**Comment by Nailington** [comment]
OOH, double compression, tasty

**Comment by Nailington** [comment]
I will get to it soon!

**Comment by Nailington** [comment]
Added!
