### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Hybird786** [Cattn/gba#92]
**Describe the bug**

Every time I click on one of the games the emulator says "Could not read content file Super_Mario_64_(USA).7z.7z"

**To Reproduce**
1. Go to '(S)NES Emulators (N64 ADDED!!!)'
2. Click on 'N64 Emulator (NEW!)'
3. Scroll down to 'Super_Mario_64_(USA).7z'

**Expected behavior**

It will pop up the emulator that is used to run the game (NOT THE GAME) 

**Screenshots**

**Windows Or Chromebook?**
Please state which device you are on

Chromebook

**Additional context**

I tried the ds emulators too and I'm getting the same thing.

**Comment by Nailington** [comment]
I am fixing this right now! Just checking though, are you using an alt server/link by chance?

**Comment by Nailington** [comment]
And this issue shouldn't exist with NDS, so if it is, that means using a custom link will not work for NDS... I'm not sure about the proper configuration. I will ping @Cattn for this.

**Comment by Hybird786** [comment]
I am using my own fork for it, so I hope that helps

**Comment by Nailington** [comment]
Oh, in that case, N64 will prob not work

**Comment by Cattn** [comment]
Hello, yeah I'd suggest forking our N64 repo (can be found on my profile or math-study)

**Comment by Cattn** [comment]
This should be fixed on our normal page
