### ISSUE TITLE
GBA Emulator[BUG]

### ISSUE THREAD

**Issue by Egghead537** [Cattn/gba#94]
whenever i try to launch a GBA game it dosen't launch and gives a error message saying it couldn't load the file and puts me in some kind of configuriation file controller 

**To Reproduce**
1. Go to Dragon ball z supersonic warriors was where i first found the issue
2. Click on start game it loads and then launches the file controller

**Windows Or Chromebook?**
i am on a chromebook

**Comment by Egghead537** [comment]
it looks to be all of them

**Comment by Cattn** [comment]
Do you have access to dev console? (Ctrl-Shift-I)?
]

**Comment by Egghead537** [comment]
no i dont 
this is a picture of what comes up
![Screenshot 2023-02-10 1 36 12 PM](https://user-images.githubusercontent.com/125046281/218182242-f17bff9b-4cd9-4d24-8b55-7326d62c3434.png)

**Comment by Egghead537** [comment]
i can move around into diffrent menus using the controls for the game such as using z for a and x for b

**Comment by Cattn** [comment]
Yeah ignore the menu it's not supposed to be there
