### ISSUE TITLE
[ROM REQUEST] Can you guys please add pokemon Infinite Fusion because I heard the game is insanely funny.

### ISSUE THREAD

**Issue by SamistheGoat** [Cattn/gba#96]
**Is this a ROM hack?**
Yes

**Do you have a link to the ROM?**
No
**Does this ROM require patching?**
I dont think so
**Anything Extra**

**Comment by alantheraboot** [comment]
Infinite fusion isn't a rom hack it is a fangame, you need to download it you cant play it on gba

**Comment by Mekomancer** [comment]
it runs on windows blud

**Comment by Mekomancer** [comment]
close this issue bruh
