### ISSUE TITLE
NDS Emulator

### ISSUE THREAD

**Issue by Luigifa** [Cattn/gba#98]
**Describe the bug**
DS Emulator doesnt save game progress

**To Reproduce**

**Expected behavior**
I had a save file for a ds game and left it. When I opened up the game again, my progress wasn't saved.

**Screenshots**

**Windows Or Chromebook?**
Chromebook

**Additional context**

**Comment by Nailington** [comment]
I have successfully saved DS games in the past... Are you sure you saved? Can you reproduce this behavior again? DO Save States work? For now, if this continues to be an issue, please use the Save State feature! This also allows you to transfer your save between our different links if neccessary.

**Comment by Luigifa** [comment]
Well i know for a fact in gta chinatown wars I put on the auto save feature the game had. I played the game for a little while, stopped and when I came back to it the next day, my save file was gone.
